language: generic
branches:
  only:
    - master
services:
  - docker
before_install:
  - docker build -t hyper-canny .
script:
  - docker run -t hyper-canny /bin/bash -c 'meson build && cd build && ninja test'
after_success:
  - docker run -t hyper-canny /bin/bash -c './scripts/coverage.sh -codecov' -e CODECOV_TOKEN
