language: cpp
before_install:
  - sudo apt-get install ninja-build python3 -y
  - sudo apt-get install libpng12-dev -y
  - sudo apt-get install libpocl-dev ocl-icd-opencl-dev opencl-headers -y
  - sudo apt-get install libnetcdf-c++4-dev -y
  - sudo apt-get install libhdf5-dev -y
  - sudo pip3 install meson
script:
  - meson build
  - cd build && ninja && ninja test
