language: cpp
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - ninja-build
            - python3
            - libpng12-dev
            - mesa-opencl-icd
            - ocl-icd-opencl-dev
            - opencl-headers
            - libnetcdf-c++4-dev
            - libhdf5-dev
before_install:
  - sudo pip3 install meson
script:
  - meson build
  - cd build && ninja && ninja test
